#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 2.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master

image: Visual Studio 2017


#---------------------------------#
#    environment configuration    #
#---------------------------------#

# this is how to allow failing jobs in the matrix
# matrix:
  # fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
  # allow_failures:
    # - platform: x86
      # configuration: Debug
    # - platform: x64
      # configuration: Release

# environment variables
environment:
  package_dir: NuGet_Packages

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: "{version}.0"
  assembly_file_version: "{version}.0"
  assembly_informational_version: "{version}"

#---------------------------------#
#       build configuration       #
#---------------------------------#

# scripts to run before build
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore --verbosity m

build_script:
  # output will be in ./src/bin/Release/netstandard2.0/publish
  - cmd: dotnet publish --configuration Release -f netstandard2.0 --no-restore

# scripts to run after build
after_build:
  - mkdir %PACKAGE_DIR%
  - nuget pack src\HMRC.ESFA.Levy.Api.Types\HMRC.ESFA.Levy.Api.Types.nuspec -OutputDirectory %PACKAGE_DIR% -BasePath src\HMRC.ESFA.Levy.Api.Types -Verbosity Detailed -Version %APPVEYOR_BUILD_VERSION% -Symbols -Properties Configuration=Release
  - nuget pack src\HMRC.ESFA.Levy.Api.Client\HMRC.ESFA.Levy.Api.Client.nuspec -OutputDirectory %PACKAGE_DIR% -BasePath src\HMRC.ESFA.Levy.Api.Client -Verbosity Detailed -Version %APPVEYOR_BUILD_VERSION% -Symbols -Properties Configuration=Release

artifacts:
  # pushing all *.nupkg files in directory
  - path: 'NuGet_Packages\*.nupkg'

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:
  provider: NuGet
  api_key:
    secure: ibqTJCWGeDimgS77s+BUYJquesF1nBz2pzDodXMA/1Wce5RpdOhu4E7cwbJj2P6Q    # encrypted nuget API Key. Encrypted using Appveyor Encrypt YAML page.
  skip_symbols: true
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/

#---------------------------------#
#  notifications configuration    #
#---------------------------------#
#notifications:
#- provider: Webhook
#  url: https://webhooks.gitter.im/e/deed811789fbedb507a1
#  on_build_success: true
#  on_build_failure: true
#  on_build_status_changed: true
