trigger:
  batch: true
  branches:
    include:
      - "*"

pr: none

workspace:
    clean: all

variables:
  buildConfiguration: 'release'
  buildPlatform: 'anycpu'

pool:
  name: 'DAS - Continuous Integration Agents'

steps:
- task: gitversion/setup@0
  displayName: gitversion/setup
  inputs:
    versionSpec: 5.5.x

- task: gitversion/execute@0
  displayName: gitversion/execute
  inputs:
    useConfigFile: true
    configFilePath: GitVersion.yml
    updateAssemblyInfo: true

- task: DotNetCoreCLI@2
  displayName: dot restore
  inputs:
    command: restore
    projects: 'src/HMRC.ESFA.Levy.Api.sln'
    noCache: true

- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    projects: 'src/**/*.csproj'
    arguments: '--configuration $(buildConfiguration)  --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    searchPatternPack: 'src/HMRC.ESFA.Levy.Api.Types/HMRC.ESFA.Levy.Api.Types.csproj;src/HMRC.ESFA.Levy.Api.Client/HMRC.ESFA.Levy.Api.Client.csproj'
    versioningScheme: byBuildNumber

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: src
    Contents: |
      **/HMRC.ESFA.Levy.Api.Types.*.nupkg
      **/HMRC.ESFA.Levy.Api.Client.*.nupkg
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
